#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

FROM ubuntu:18.04

ARG sdk_version=0.13.0

WORKDIR /home/sdk

COPY target/healthcare-claims-processing.dar /home/sdk/

RUN /bin/bash -c "apt-get update --no-show-upgraded &&  apt-get install curl openjdk-8-jdk -y"
RUN /bin/bash -c "curl -L https://github.com/digital-asset/daml/releases/download/v${sdk_version}/daml-sdk-${sdk_version}-linux.tar.gz -o daml-sdk-${sdk_version}-linux.tar.gz && \
                  tar -zxvf daml-sdk-${sdk_version}-linux.tar.gz && \
                  cd sdk-${sdk_version} && \
                  ./install.sh && \
                  cd - && \
                  rm -rf sdk-${sdk_version}"

EXPOSE 7600

CMD ~/.daml/bin/daml sandbox -- --port 7600 --scenario DemoOnboardScenario.InsurancePolicies:insurancePoliciesSetSingle healthcare-claims-processing.dar
