#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

version: '2'
services:
  hcp-sandbox:
    image: digitalasset/healthcare-claims-processing-sandbox:0.0.1
    build:
      context: .
      dockerfile: sandbox.Dockerfile
    ports:
      - "127.0.0.1:6865:6865"
      - "127.0.0.1:7500:7500"
  hcp-triggers:
    image: digitalasset/healthcare-claims-processing-triggers:0.0.1
    build:
      context: .
      dockerfile: triggers.Dockerfile
    depends_on:
      - "hcp-sandbox"
    environment:
      - LEDGER_HOST=hcp-sandbox
      - LEDGER_PORT=6865
