#
# Copyright (c) 2019, Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#

FROM ubuntu:18.04

WORKDIR /home/sdk

COPY target/healthcare-claims-processing.dar /home/sdk/

RUN /bin/bash -c "apt-get update --no-show-upgraded &&  apt-get install curl openjdk-8-jdk -y"
RUN /bin/bash -c "curl -L https://github.com/digital-asset/daml/releases/download/v0.12.25/daml-sdk-0.12.25-linux.tar.gz -o daml-sdk-0.12.25-linux.tar.gz && \
                  tar -zxvf daml-sdk-0.12.25-linux.tar.gz && \
                  cd sdk-0.12.25 && \
                  ./install.sh && \
                  cd - && \
                  rm -rf sdk-0.12.25"

EXPOSE 7600

CMD ~/.daml/bin/daml sandbox -- --port 7600 --scenario DemoOnboardScenario.InsurancePolicies:insurancePoliciesSetSingle healthcare-claims-processing.dar
